### ISSUE TITLE
Savegame startet nicht mit TerraLifePlus

### ISSUE THREAD

**Issue by JoFrixx1** [FarmingAgency/FS22_TerraLifePlus_Documentation#1]
Moin,
Ich habe mir heute TerraLifePlus heruntergeladen und wollte ein Savegame auf der Irgendwo in Thüringen starten, jedoch wenn es läd bleibt es immer bei 20% stehen. Ich kann dann auch nicht mehr aus dem Spiel raus-tabben oder es mit ALT+F4 beenden. Ich muss das Spiel über den Taskmanager schließen.
Ich habe nur die benötigten Mods aktiviert und auch sonst keine Modifikation am Basegame vorgenommen

Hier ist die Logdatei nachdem ich den LS über den Taskmanager geschlossen habe
[log.txt](https://github.com/user-attachments/files/16825008/log.txt)

Hier ist ein Screenshot von der Konsole wenn es aufhört zu laden
![Screenshot 2024-08-31 161806](https://github.com/user-attachments/assets/97a39d3f-1c09-4042-ac85-50ccc6c4b2c3)

**Comment by braeven** [comment]
Bitte GrafikTreiber aktualisieren wenn möglich
wenn dies nicht klappt, dann bitte:
Change your game.xml(can be found in the same folder as the log.txt) from <renderer>D3D_12</renderer> to <renderer>D3D_11</renderer>, this helped for a lot of players.

wenn es dann auch nicht klappt bitte im MaizePlus Discrod melden für schnellere Hilfe
