### ISSUE TITLE
Holzer map - unable to fill stable without animals

### ISSUE THREAD

**Issue by bandit420** [FarmingAgency/FS22_TerraLifePlus_Documentation#10]
When playing "Unterreiterhof" it is not possible to fill in cow food (e.g. fresh gras or hay) when there is no animal in the stables.

Not sure if this is intended or a bug.

If 1 or more animal is added, the filling process works as expected.

**Comment by braeven** [comment]
it's intended with our extended feeding

**Comment by bandit420** [comment]
All right, thank you for confirming.

Will close this one then.

Really enjoying TerraLifePlus so far, keep on modding. :)
