### ISSUE TITLE
Where to unload 'Milk Replacer Powder' on map 'Somewhere In Thuringia III TerraLifePlus'?

### ISSUE THREAD

**Issue by DeckerMMIV** [FarmingAgency/FS22_TerraLifePlus_Documentation#2]
_I am unsure if my issue described below belongs here. If not then please just close this issue, and/or consider it for an item to the FAQ for TerraLife Plus._

I have no prior knowledge nor experience with 'TerraLife Plus' nor the map 'Somewhere In Thuringia III TerraLifePlus', so this is a "complete newbie" attempt with trying to figure out both the "workflow of feeding animals" and where to find the map's individual unload-areas.

In a singleplayer session on 'Somewhere In Thuringia III TerraLifePlus', I bought five female calfs _(one of each type)_ and one male calf. - Then I looked at the required food requirements and from that bought from the store; calf hay, calf feed & milk replacer powder.

The calf hay pallet was easily unloaded at the animal barn's inside indicated unload point.

The calf feed pallet wouldn't unload ... it took me some time to understand, that I needed to "remove object" of the pallet to get a smaller bag, which then would successfully be accepted at the unload point.

However for the milk replacer powder, when having a smaller bag of it, none of the three (four?) unload points at the barn will accept it. - So I wonder if I am missing some other step to do, or if there is another (fifth?) unload point to use for the milk replacer powder to be accepted?

![MilkPowder_unload_point_problem_01](https://github.com/user-attachments/assets/5d5c459c-87a7-4406-a028-4adcff9018c8)

![MilkPowder_unload_point_problem_02](https://github.com/user-attachments/assets/8a38a0bb-54f7-4b2f-b442-d5e523118a96)

**Comment by braeven** [comment]
Milk Replacer Powder is not feeded directly.
you need a milk-taxi vehicle to make it into a liquid.
Just buy one of the 2 option, drive next to the bags and fill it. Water will be added automatically

**Comment by DeckerMMIV** [comment]
I see. Thank you for the hint.

I suppose 'milk-taxi' is an internal name, or a word-by-word translation from German to English, as I found them in the vehicle-shop under category 'Animals' with the name 'Milk Wagon'.

With that solved, I did some more "newbie / monkey testing" and got confused with the following:

Thinking that I still have to "remove object" from the pallet of 'Milk Replacer Powder', to get a smaller bag - to then fill into the 'milk-taxi / Milk Wagon', it apparently wouldn't fill to more than approx. 16 litres (or 33 for the larger Milk Wagon).

That I think I've figured out, having looked at the `milkTaxi.lua` script, due to that script is "converting" the fill-type from  `MILKREPLACER_POWDER` to `MILKREPLACER`. - I am now guessing that the filling procedure using the vanilla game scripts are "blocking / preventing" further filling, due to the fill-types between "source" and "destination" are now different, as the "destination" contains more than 5% _(or is it only 3%?)_ which therefore cannot forcefully switch to a different fill-type.

So I discovered that apparently to fill a milk-taxi / Milk Wagon it has to be truly empty and be nearby the pallet of Milk Replacer Powder, and should be filled to 100% to correctly make use of the "water will be added automatically" _(simulated by the x5 factor in the `milkTaxi.lua` script I suppose.)_

Perhaps you can use what I wrote above for an FAQ, as I imagine other players _(new to TerraLife Plus)_ will likely get confused about using the 'Milk Replacer Powder' and 'Milk Wagons' as I was.

_Image of what **does not work** as expected, using the smaller bag:_
![image](https://github.com/user-attachments/assets/cf360350-5b20-4624-8f2e-17f5e1001d84)

**Comment by braeven** [comment]
most vehicles need to be empty before you can fill them with something else

We will add this to the wiki we are preparing, how to get liquid milk replacer.

you don't need to use individual bags, you can still use the full pallets, but I can see why someone would try using the individual bags

**Comment by GonivolkNikolay** [comment]
There may be a mistake in pallets at store with MILKREPLACER bags
For deuka milk replacer in its fillUnit fillType list we have
MILKREPLACER_POWDER
But for another version in store we have MILKREPLACER fillType

For deuka MILKREPLACER_POWDER
Line 34: FS22_TerraLifePlus_Assets.zip\deuka\MultiBuyFood.xml

For analoge MILKREPLACER
Line 31: FS22_TerraLifePlus_Assets.zip\deuka\grainBags\MultiBuyGrist.xml
