### ISSUE TITLE
Don't Start Server

### ISSUE THREAD

**Issue by ASanta79** [FarmingAgency/FS22_TerraLifePlus_Documentation#3]
Hello, I have a server on g_portal where I run the Farming derver.
Today, seeing the map updated with terralife, and having never played it, I wanted to try to load it.
I load all the required mods except the "Holzer TerrelifePlus" and the "terralifePlus" tells me that it is impossible to load them because they have dependencies that must be loaded together. I have sifted through the list of mods three times but I can't understand why the server doesn't start.....

any idea for stating?

![immagine](https://github.com/user-attachments/assets/84c39266-0b80-49ba-a292-7026c8ad6b13)
![immagine](https://github.com/user-attachments/assets/35b52aac-d625-46af-92ed-4e90976765e1)

**Comment by braeven** [comment]
you are missing several mods, like the assets pack, utils pack and other required mods.

best would be to start a singleplayer game first with the mod and use the ingame-modhub and download everything needed and upload it to the server

**Comment by ASanta79** [comment]
hi, I loaded all the mods that are in the request, except those two because it tells me they have dependencies

![immagine](https://github.com/user-attachments/assets/ce7f1e42-54b8-4221-b6d6-60e7fdbfc195)


I'll try to remove the mods folder and start a multiplayer from the local to see what it loads, as you advised me then I'll tell you if it works. I'll try thanks for the idea

**Comment by ASanta79** [comment]
I finally solved it, I don't know why 2 mods even if present in the folder the server didn't see them... I removed everything and copied the files directly into the new mods folder and everything worked

thanks a lot for the help
