### ISSUE TITLE
Mixer Wagon & Recipes - Overlapping fill-types causing issues?

### ISSUE THREAD

**Issue by DeckerMMIV** [FarmingAgency/FS22_TerraLifePlus_Documentation#4]
I was trying to produce some 'Mixed ration dairy calves from month 4', by buying the ingredients directly from vehicle-shop and then filling into a mixer wagon.

I found two issues with this;

1) The helpful display could use some 'comma' or 'dash' delimiter between the individual types of input, as it is difficult to distinguish between them. - Please ask your Lua scripters to look into maybe using the `table.concat({table}, {delimiter})` method for string concatination, compared to using the `..` operator.

2) Other issue, a little "game breaking" I think. There are some recipes categories which accept the same input-types. This seems to prevent me from filling into a specific category, when the fill-type was already used for a different category.
Example in the image, where I now cannot fill into category 'Cereal protein', as those input fill-types will instead be used for category 'Cereal energy'.

![image](https://github.com/user-attachments/assets/d99d1c17-b77b-4059-abd5-d080a54d7d0e)

I haven't tried yet, but I suppose I should have used 'CCM', 'Canola' or 'Sunflower' first as input, **before** using 'Grain Grist', 'deuka Graingrist' or 'Sorghum'?

![image](https://github.com/user-attachments/assets/64015256-cfe4-4032-84aa-93f884a3cd13)

**Comment by braeven** [comment]
We are looking into this problem, but the guys who made the feeding is not around today, so we don't know what to change right
