### ISSUE TITLE
Copy Paste error in TerraLifePlus_Assets?

### ISSUE THREAD

**Issue by rocomer823** [FarmingAgency/FS22_TerraLifePlus_Documentation#5]
Amazing work! I believe there was a copy paste error
In TerraLifePlus_Assets in the deuka folder, MultiBuyFood xml, line 315
is			<option filename="deuka/euroPallets/deukaBag_chicken.xml" fillUnit="2" design="2"/
should be	<option filename="deuka/euroPallets/deukaBag_sheep.xml" fillUnit="2" design="2"/

With the current way when you try to buy a single bag of Sheep Starter you get a bag of chicken feed instead.

**Comment by braeven** [comment]
Thank you, will be corrected in an update
