### ISSUE TITLE
Opening Map

### ISSUE THREAD

**Issue by Thinus69** [FarmingAgency/FS22_TerraLifePlus_Documentation#6]
I have various MODS installed. When opening a saved or new Terra Life Map it runs through up to certain % and then terminate FS22 as a whole. Can somebody maybe list all mods not be used with Terra Life Maps

**Comment by Timmeey86** [comment]
@Thinus69 Are you on discord? If so, join https://discord.gg/XkUK5AYs4s and once that's done and once you have reacted to the proper rules posts, follow this link, please:
https://discord.com/channels/699589863996915713/1280211388945399919/1280212032846561280

Otherwise, post your log.txt here

**Comment by braeven** [comment]
no comment after 4 days
->closed
