### ISSUE TITLE
Mistake in store pallets with MILKREPLACER

### ISSUE THREAD

**Issue by GonivolkNikolay** [FarmingAgency/FS22_TerraLifePlus_Documentation#8]
In store we have variants of pallets with milk replacer powder

For deuka milk replacer in its fillUnit fillType list we have
MILKREPLACER_POWDER
But for another version in store we have MILKREPLACER fillType

For deuka MILKREPLACER_POWDER
Line 34: FS22_TerraLifePlus_Assets.zip\deuka\MultiBuyFood.xml

For analoge MILKREPLACER
Line 31: FS22_TerraLifePlus_Assets.zip\grainBags\MultiBuyGrist.xml

**Comment by braeven** [comment]
will be fixed with an update
